### ISSUE TITLE
Bug: InActive User Management - Add only ignored by default user: SQL Error

### ISSUE THREAD

**Issue by DrDeath** [andreaskou/PHPBB_IUM#14]
Add a "ignored by default" user on the InActive User Management --> Add users to ignore list

Add only 1 user (i.E. an Administrator or Global Moderator) the the "Add users to ignore list" and click on the Button "Add to List".

SQL Error:

`SQL ERROR [ mysqli ]
[0]
SQL
No values specified for SQL IN comparison
`

**Comment by andreaskou** [comment]
Thanks!
Fix is on its way.
Just a few adjustments.
From now on, if a user is in an ignored group it will show a message.

**Comment by DrDeath** [comment]
Maybe a leftover?  ---> ignore_user.php on line 93: Undefined variable: test

**Comment by DrDeath** [comment]
Should I re-open (create a new)  issue?
`/classes/ignore_user.php on line 93: Undefined property: andreask/ium/classes/ignore_user::$u_action`

**Comment by andreaskou** [comment]
Hi,
Im terribly sorry but I just saw this.
Is this happening under the same conditions?

**Comment by DrDeath** [comment]
yes. I tried to add an Admin and an Moderator to the ignored list.
Both are filtere out, the user Message Shows up, that no user is left to add to the ignore list.
And in Top of the ACP the error Message is shown:

`[phpBB Debug] PHP Notice: in file [ROOT]/ext/andreask/ium/classes/ignore_user.php on line 93: Undefined variable: test
[phpBB Debug] PHP Notice: in file [ROOT]/ext/andreask/ium/classes/ignore_user.php on line 93: Undefined property: andreask/ium/classes/ignore_user::$u_action`

**Comment by DrDeath** [comment]
See:
https://github.com/andreaskou/PHPBB_IUM/blob/d4ab73eebd4972b8e03338f9165d2edcb6ff0448/classes/ignore_user.php#L93
