### ISSUE TITLE
Bug2: InActive User Management - Add only ignored by default user:  UNDEFINED

### ISSUE THREAD

**Issue by DrDeath** [andreaskou/PHPBB_IUM#16]
Version 1.1.4
If you put an ignored user to the ingore user list you'l receive php Errors:
See issue #14 

```
[phpBB Debug] PHP Notice: in file [ROOT]/ext/andreask/ium/classes/ignore_user.php on line 93: Undefined variable: test
[phpBB Debug] PHP Notice: in file [ROOT]/ext/andreask/ium/classes/ignore_user.php on line 93: Undefined property: andreask/ium/classes/ignore_user::$u_action
```

**Comment by DrDeath** [comment]
See branch stable:
https://github.com/andreaskou/PHPBB_IUM/blob/d4ab73eebd4972b8e03338f9165d2edcb6ff0448/classes/ignore_user.php#L93

**Comment by andreaskou** [comment]
Hi, 

I don't know why but for some reason I don't get any e-mails from git.
So I just saw this.
As soon as I have some time probably in the next couple of days I'll fix it.

All the best!

And thanks again for finding all the little bugs!

**Comment by DrDeath** [comment]
you're welcome... take our time

**Comment by andreaskou** [comment]
So now that I have the will to do some work, yes this is a leftover it can be ignored.
Or even removed.
I gave this version for validation. If the ext will not pass it I ll fix it and submit it again.
If i does pass the validation it´s not that of a big deal! :)
