### ISSUE TITLE
phpbb 3.3.1 - Error After activation

### ISSUE THREAD

**Issue by DrDeath** [andreaskou/PHPBB_IUM#19]
Getting following error after phpBB Update from 3.3.0 to 3.3.1:  ( PHPBB_IUM was installed and active before update phpBB 3.3.0 to phpBB 3.3.1 )

Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException: Circular reference detected for service "andreask.ium.cron.send_reminder", path: "andreask.ium.cron.send_reminder -> 

andreask.ium.classes.reminder -> controller.helper -> cron.manager -> andreask.ium.cron.send_reminder". in /var/www/web773/htdocs/phpbb33/vendor/symfony/dependency-injection/Container.php:297 Stack trace: #0 

/var/www/web773/htdocs/phpbb33/vendor/symfony/dependency-injection/ContainerBuilder.php(606): Symfony\Component\DependencyInjection\Container->get('andreask.ium.cr...', 2) #1 

/var/www/web773/htdocs/phpbb33/vendor/symfony/dependency-injection/ContainerBuilder.php(588): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('andreask.ium.cr...', 1) #2 

/var/www/web773/htdocs/phpbb33/phpbb/di/service_collection.php(57): Symfony\Component\DependencyInjection\ContainerBuilder->get('andreask.ium.cr...') #3 

/var/www/web773/htdocs/phpbb33/phpbb/di/service_collection_iterator.php(44): phpbb\di\service_c in /var/www/web773/htdocs/phpbb33/vendor/symfony/dependency-injection/Container.php on line 297

**Comment by andreaskou** [comment]
Yes this is a known issue of phpbb.
https://tracker.phpbb.com/browse/PHPBB3-16565
I'm working on a workaround but unfortunately I don't have a lot of spare time. So as soon as I have an update I'll post it on phpbb.

**Comment by andreaskou** [comment]
Hello,

https://github.com/andreaskou/PHPBB_IUM/tree/ium_RC3
Was uploaded, this makes it compatible with phpbb 3.3.1
Please also read this...
https://www.phpbb.com/community/viewtopic.php?p=15594486#p15594486
