### ISSUE TITLE
Phpbb 3.3 compatible

### ISSUE THREAD

**Issue by wads24** [andreaskou/PHPBB_IUM#20]
Wonderful extension, andres!  Any plans to make it compatible with 3.3.1?
Thanks in advance for the replay

**Comment by andreaskou** [comment]
Hi thanks,
I'll try to have a workaround as soon as possible. Unfortunately I don't have much spare time for the moment.

**Comment by andreaskou** [comment]
Hello,

https://github.com/andreaskou/PHPBB_IUM/tree/ium_RC3
Was uploaded, this makes it compatible with phpbb 3.3.1
Please also read this...
https://www.phpbb.com/community/viewtopic.php?p=15594486#p15594486
